Cloud9/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cloud9.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Cloud9/Controllers/PlaneController.cs
using System.Collections.Generic;
using System.Linq;
using Cloud9.Models;
using Cloud9;
using Cloud9.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
//using NPOI.SS.Formula.Functions;

namespace Cloud9.Controllers
{
    public class PlaneController : Controller
    {
        private readonly Cloud9Context _context;

        public PlaneController(Cloud9Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var planesContext = _context.Planes.Include(a => a.type).Include(a => a.seatMap);
            return View(await planesContext.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            Plane plane = await _context.Planes.Include(p => p.type).Include(a => a.seatMap).FirstOrDefaultAsync(p => p.ID == id);
            return View(plane);
        }


        [Authorize(Roles = "True")]
        public IActionResult Create()
        {
            ViewData["typeID"] = new SelectList(_context.Set<PlaneType>(), "ID", "name");
            return View();
        }


        // POST: Planes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "True")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("color, typeID, price, range, seatMapId")] Plane plane)
        {
            if (ModelState.IsValid)
            {
                var newSeatMap = new SeatMap() { numSeats = plane.seatMapId };
                _context.SeatMaps.Add(newSeatMap);
                plane.seatMapId = newSeatMap.ID;
                plane.seatMap = newSeatMap;
                _context.Add(plane);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["typeID"] = new SelectList(_context.Set<PlaneType>(), "ID", "name", plane.type);
            return View(plane);
        }


        [Authorize(Roles = "True")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plane = await _context.Planes.FindAsync(id);
            if (plane == null)
            {
                return NotFound();
            }

            var seatMapList = new List<SelectListItem> { };
            foreach (var seatMap in _context.SeatMaps.ToList())
            {
                seatMapList.Add(new SelectListItem
                {
                    Value = seatMap.ID.ToString(),
                    Text = seatMap.numSeats.ToString(),
                });
            }

            ViewBag.SeatMap = seatMapList;
            ViewData["typeID"] = new SelectList(_context.Set<PlaneType>(), "ID", "name", plane.type);
           
            return View(plane);
        }

        // POST: Planes/Edit/5
        [Authorize(Roles = "True")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID, color, typeID, price, range, seatMapId")] Plane plane)
        {
            if (id != plane.ID)
            {
                return NotFound();
            }

            if (HttpContext.User.FindFirst(ClaimTypes.Role).Value != "True")
            {
                return View("~/Views/Users/AccessDenied.cshtml");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(plane);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlaneExists(plane.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["typeID"] = new SelectList(_context.Set<PlaneType>(), "ID", "name", plane.type);
            ViewData["seatMapId"] = new SelectList(_context.Set<PlaneType>(), "ID", "numSeats", plane.seatMap);
            return View(plane);
        }

        [Authorize(Roles = "True")]
        // GET: Planes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (HttpContext.User.FindFirst(ClaimTypes.Role).Value != "True")
            {
                return View("~/Views/Users/AccessDenied.cshtml");
            }

            var plane = await _context.Planes
                .Include(a => a.type)
                .Include(a => a.seatMap)
                .FirstOrDefaultAsync(p => p.ID == id);
            if (plane == null)
            {
                return NotFound();
            }

            return View(plane);
        }

        // POST: Planes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plane = await _context.Planes.FindAsync(id);
            _context.Planes.Remove(plane);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlaneExists(int id)
        {
            return _context.Planes.Any(p => p.ID == id);
        }

        [Authorize]
        public async Task<IActionResult> Buy(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plane = await _context.Planes
                .Include(a => a.type)
                .Include(a => a.seatMap)
                .FirstOrDefaultAsync(p => p.ID == id);
            if (plane == null)
            {
                return NotFound();
            }

            return View(plane);
        }

        //POST: Planes/Buy/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Buy(int id, Plane plane)
        {   
            if (id != plane.ID)
            {
                return NotFound();
            }
            var newPlane = new List<Plane>();
            newPlane.Add(_context.Planes.Include(p => p.type).FirstOrDefault(o => o.ID == plane.ID));

            Order newOrder = new Order { userID = Int16.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value)
                , purchasedAt = DateTime.Now,
                planeId = plane.ID};


            newOrder.planes = newPlane;
            _context.Orders.Add(newOrder);
            await _context.SaveChangesAsync();
            return RedirectToRoute("Default", new { controller = "Order", action = "Index" });
        }


        public IActionResult getPlaneColors()
        {
            return Json(new { Data = _context.Planes
                .GroupBy(p => p.color).Select
                (p => new { label = p.Key, value = p.Count() }).ToList(), success = true });
        }

       // [HttpPost]
        //POST: Plane/SerachPlanes
        public IActionResult SearchPlanes(string type, string price, string color)
        {
            var serachResults = _context.Planes.Include(plane => plane.type).Include(a => a.seatMap)
                    .Where(plane => (string.IsNullOrEmpty(type) || plane.type.name.Contains(type))
            && (string.IsNullOrEmpty(color) || plane.color.Contains(color))
            && (string.IsNullOrEmpty(price) || plane.price == Int16.Parse(price))).ToList();

            return Json(new { data = serachResults, success = true });
        }
    }
}

Cloud9/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cloud9.Data;
using Cloud9.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace Cloud9.Controllers
{
    public class UsersController : Controller
    {
        private readonly Cloud9Context _context;

        public UsersController(Cloud9Context context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            if (HttpContext.User.FindFirst(ClaimTypes.Role).Value != "True")
            {
                return View("~/Views/Users/AccessDenied.cshtml");
            }

            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (HttpContext.User.FindFirst(ClaimTypes.Role).Value != "True")
            {
                return View("~/Views/Users/AccessDenied.cshtml");
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            if (HttpContext.User.FindFirst(ClaimTypes.Role).Value != "True")
            {
                return View("~/Views/Users/AccessDenied.cshtml");
            }

            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,userID,name,email,password,isAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (HttpContext.User.FindFirst(ClaimTypes.Role).Value != "True")
            {
                return View("~/Views/Users/AccessDenied.cshtml");
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,userID,name,email,password,isAdmin")] User user)
        {
            if (id != user.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (HttpContext.User.FindFirst(ClaimTypes.Role).Value != "True")
            {
                return View("~/Views/Users/AccessDenied.cshtml");
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.ID == id);
        }


        public async Task<IActionResult> Logout()
        {
            //HttpContext.Session.Clear();

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login");
        }

        // GET: Users/Login
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        // POST: Users/Login
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("ID,email,password")] User user)
        {
            if (ModelState.IsValid)
            {

                var currentUser = await _context.Users.FirstOrDefaultAsync(u => u.email == user.email && u.password == user.password);
                // var q = 1;
                if (currentUser != null)
                {

                    Signin(currentUser);

                    return RedirectToAction(nameof(Index), "Home");
                }
                else
                {
                    ViewData["Error"] = "Username and/or password are incorrect.";
                }
            }
            return View(user);
        }

        private async void Signin(User account)
        {
            var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, account.email),
                    new Claim(ClaimTypes.Role, account.isAdmin.ToString()),
                    new Claim(ClaimTypes.NameIdentifier, account.ID.ToString())
                };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10)
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }

        // GET: Users/Register
        public IActionResult Register()
        {
            return View();
        }

        // POST: Users/Register
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("ID,userID,name,email,password")] User user)
        {
            if (ModelState.IsValid)
            {

                var currentUser = _context.Users.FirstOrDefault(u => u.email == user.email);

                if (currentUser == null)
                {
                    _context.Add(user);
                    await _context.SaveChangesAsync();

                    var u = _context.Users.FirstOrDefault(u => u.email == user.email && u.password == user.password);

                    Signin(u);

                    return RedirectToAction(nameof(Index), "Home");
                }
                else
                {
                    ViewData["Error"] = "This email adress already exits. Please Signin or enter another email adress";
                }
            }
            return View(user);
        }
    }
}

Cloud9/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cloud9.Controllers
{
    public class WeatherController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Cloud9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cloud9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <link rel="stylesheet" href="~/css/layout.css" type="text/css" />
    <link rel="stylesheet" href="~/css/home.css" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 nav-color">
            <div class="container">
                <a class="navbar-brand white" asp-area="" asp-controller="Home" asp-action="Index">Cloud9</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark white" asp-area="" asp-controller="Plane" asp-action="Index">Planes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark white" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark white" asp-area="" asp-controller="About" asp-action="Index">About us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark white" asp-area="" asp-controller="Contact" asp-action="Index">Contact us</a>
                    </li>
                    @if (Context.User.IsInRole("True"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark white" asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a>
                            </li>
            }
            else
            {

            }
                    <li class="nav-item">
                        <a class="nav-link text-dark white" asp-area="" asp-controller="Weather" asp-action="Index">Weather</a>
                    </li>
                    @if (Context.User.Claims != null && Context.User != null && Context.User.Claims.Count() > 0)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark white" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark white" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                        </li>
                    }

                </ul>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Cloud9/Views/Shared/_LoginLayout.cshtml
﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cloud9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
@RenderBody()
</main>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>